#!/bin/sh

bspc rule -r "*"

bspstart &

#### MONITORS ####
for monitor in $(bspc query -M)
do
    # set the workspaces on each monitor to 1-9
    bspc monitor $monitor -d 1 2 3 4 5 6 
done

###-----Global Setiings
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none


bspc config border_width       3
bspc config window_gap        12
bspc config split_ratio     0.50

config borderless_monocle true
config gapless_monocle true
config single_monocle false

config focus_follows_pointer true

config top_padding 20
config left_padding 20
config right_padding 20

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
