#!/bin/bash
# wm independent hotkeys
#

# terminal emulator
super + Return
	st

# program launcher
super + d
	bspmenu

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#
# bspwm hotkeys
#

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + q
	bspc node -c

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next


# window swallowing
  
#
# state/flags
#

# focus the node in the given direction
super + {Left,Down,Up,Right}
	bspc node -f {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous window in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local.!hidden.window

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-6}
	bspc {desktop -f,node -d} '^{1-6}'

#
# preselect
#

# preselect the direction
#super + ctrl + {h,j,k,l}
#	bspc node -p {west,south,north,east}

# preselect the ratio
#super + ctrl + {1-9}
#	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
#super + ctrl + space
#	bspc node -p cancel

# cancel the preselection for the focused desktop
# super + ctrl + shift + space
	#bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#
# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# resize windows
super + shift + {Left,Down,Up,Right}
  { bspshrinkx, bspexpandy, bspshrinkx, bspexpandx }

# Workspaces
super + {_,shift + }{1-6}
  bspc {desktop -f,node -d} 'focused:^{1-6}'

# hide/unhide windows
# hide window
super + e
  bspc node -g hidden

# unhide window
super + shift + e
  bspc node {,$(bspc query -N -n .hidden | tail -n1)} -g hidden=off

